# Assignment 8 python programming.

# 1.Write a Python Program to Add Two Matrices?


## Answer

In [2]:
import numpy as np

X= [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y= [[9,8,7],
    [6,5,4],
    [3,2,1]]


add=np.add(X,Y)

print(add)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


# 2.Write a Python Program to Multiply Two Matrices?

## Answer

In [4]:
import numpy as np

X= [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y= [[9,8,7],
    [6,5,4],
    [3,2,1]]


Multiply=np.multiply(X,Y)

print(Multiply)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


# 3.Write a Python Program to Transpose a Matrix?

## Answer

In [5]:
import numpy as np

X= [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]
 

Tranpose=np.transpose(X)

print(Tranpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# 4.Write a Python Program to Sort Words in Alphabetic Order?

## Answer

In [7]:

my_str = input("Enter a sentance: ") ### Asking the user for sentence


words = [word.lower() for word in my_str.split()] ### breaking the sentence into a list of words


words.sort() ### Sorting the list



print("The sorted words are:")
for word in words:
    print(word)


Enter a sentance: I am the best data scientist in the world. 
The sorted words are:
am
best
data
i
in
scientist
the
the
world.


#  5.Write a Python Program to Remove Punctuation From a String?

## Answer

In [10]:

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~''' ### All the punctuations

### my_str = "Hello!!!, he said ---and went."   made one if someon is being lazy ;-p


my_str = input("Enter a sentence with punctutions: ") ### Asking the user

# remove punctuation from the string
without_punct = ""
for char in my_str:
    if char not in punctuations:
        without_punct = without_punct + char


print(without_punct)



Enter a sentence with punctutions: Hello!!!, he said ---and went.
Hello he said and went
